[package]
version = "0.2.1"

name = "fast-floats"
license = "MIT OR Apache-2.0"
authors = ["bluss", "unic0rn9k"]
edition = "2021"

documentation = "https://docs.rs/fast-floats/"

description = "Fast-math wrappers for floats; experimental and unstable; for experiments."
